services:

  auth:
    build:
      context: ./backend/NutriHubAuth
      dockerfile: Dockerfile
    ports:
      - "5225:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  patient:
    build:
      context: ./backend/NutriHubPatient
      dockerfile: Dockerfile
    ports:
      - "5081:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped

  clinic:
    build:
      context: ./backend/NutriHubClinic
      dockerfile: Dockerfile
    ports:
      - "5249:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    restart: unless-stopped
