// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NutriHubPatient.Infrastructure.Data;

#nullable disable

namespace NutriHubPatient.Infrastructure.Migrations
{
    [DbContext(typeof(PatientDbContext))]
    [Migration("20260504015708_FoodGuidPrimaryKey")]
    partial class FoodGuidPrimaryKey
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("nutri_patient")
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.DailySummary", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CalorieGoal")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("TotalCarbsG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("TotalFatG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("TotalProteinG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("WaterMl")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "Date")
                        .IsUnique();

                    b.ToTable("DailySummaries", "nutri_patient");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.Food", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<double>("CaloriesPer100g")
                        .HasColumnType("double precision");

                    b.Property<double>("CarbsPer100g")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByPatientId")
                        .HasColumnType("uuid");

                    b.Property<double>("FatPer100g")
                        .HasColumnType("double precision");

                    b.Property<bool>("IsCustom")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<double>("ProteinPer100g")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByPatientId");

                    b.HasIndex("Name");

                    b.ToTable("Foods", "nutri_patient");

                    b.HasData(
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000001"),
                            CaloriesPer100g = 130.0,
                            CarbsPer100g = 28.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Arroz Branco Cozido",
                            ProteinPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000002"),
                            CaloriesPer100g = 77.0,
                            CarbsPer100g = 14.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.5,
                            IsCustom = false,
                            Name = "Feijão Cozido",
                            ProteinPer100g = 5.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000003"),
                            CaloriesPer100g = 165.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.6000000000000001,
                            IsCustom = false,
                            Name = "Frango Grelhado",
                            ProteinPer100g = 31.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000004"),
                            CaloriesPer100g = 143.0,
                            CarbsPer100g = 0.69999999999999996,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 10.0,
                            IsCustom = false,
                            Name = "Ovo Inteiro",
                            ProteinPer100g = 13.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000005"),
                            CaloriesPer100g = 89.0,
                            CarbsPer100g = 23.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Banana",
                            ProteinPer100g = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000006"),
                            CaloriesPer100g = 52.0,
                            CarbsPer100g = 14.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Maçã",
                            ProteinPer100g = 0.29999999999999999
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000007"),
                            CaloriesPer100g = 300.0,
                            CarbsPer100g = 57.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.5,
                            IsCustom = false,
                            Name = "Pão Francês",
                            ProteinPer100g = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000008"),
                            CaloriesPer100g = 61.0,
                            CarbsPer100g = 4.7999999999999998,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.2999999999999998,
                            IsCustom = false,
                            Name = "Leite Integral",
                            ProteinPer100g = 3.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000009"),
                            CaloriesPer100g = 163.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 5.2000000000000002,
                            IsCustom = false,
                            Name = "Carne Bovina Patinho",
                            ProteinPer100g = 28.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000010"),
                            CaloriesPer100g = 87.0,
                            CarbsPer100g = 20.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Batata Inglesa Cozida",
                            ProteinPer100g = 1.8999999999999999
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000011"),
                            CaloriesPer100g = 86.0,
                            CarbsPer100g = 20.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Batata Doce Cozida",
                            ProteinPer100g = 1.6000000000000001
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000012"),
                            CaloriesPer100g = 15.0,
                            CarbsPer100g = 2.8999999999999999,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Alface",
                            ProteinPer100g = 1.3999999999999999
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000013"),
                            CaloriesPer100g = 18.0,
                            CarbsPer100g = 3.8999999999999999,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Tomate",
                            ProteinPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000014"),
                            CaloriesPer100g = 41.0,
                            CarbsPer100g = 10.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Cenoura",
                            ProteinPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000015"),
                            CaloriesPer100g = 55.0,
                            CarbsPer100g = 11.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.59999999999999998,
                            IsCustom = false,
                            Name = "Brócolis Cozido",
                            ProteinPer100g = 3.7000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000016"),
                            CaloriesPer100g = 389.0,
                            CarbsPer100g = 66.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 7.0,
                            IsCustom = false,
                            Name = "Aveia",
                            ProteinPer100g = 17.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000017"),
                            CaloriesPer100g = 59.0,
                            CarbsPer100g = 3.6000000000000001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.40000000000000002,
                            IsCustom = false,
                            Name = "Iogurte Natural Desnatado",
                            ProteinPer100g = 10.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000018"),
                            CaloriesPer100g = 280.0,
                            CarbsPer100g = 2.2000000000000002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 20.0,
                            IsCustom = false,
                            Name = "Queijo Mussarela",
                            ProteinPer100g = 22.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000019"),
                            CaloriesPer100g = 208.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 13.0,
                            IsCustom = false,
                            Name = "Salmão",
                            ProteinPer100g = 20.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000020"),
                            CaloriesPer100g = 132.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2.0,
                            IsCustom = false,
                            Name = "Atum em Lata",
                            ProteinPer100g = 28.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000021"),
                            CaloriesPer100g = 717.0,
                            CarbsPer100g = 0.10000000000000001,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 81.0,
                            IsCustom = false,
                            Name = "Manteiga",
                            ProteinPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000022"),
                            CaloriesPer100g = 884.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 100.0,
                            IsCustom = false,
                            Name = "Azeite de Oliva",
                            ProteinPer100g = 0.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000023"),
                            CaloriesPer100g = 47.0,
                            CarbsPer100g = 12.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Laranja",
                            ProteinPer100g = 0.90000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000024"),
                            CaloriesPer100g = 32.0,
                            CarbsPer100g = 7.7000000000000002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Morango",
                            ProteinPer100g = 0.69999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000025"),
                            CaloriesPer100g = 69.0,
                            CarbsPer100g = 18.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.20000000000000001,
                            IsCustom = false,
                            Name = "Uva",
                            ProteinPer100g = 0.69999999999999996
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000026"),
                            CaloriesPer100g = 43.0,
                            CarbsPer100g = 11.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Mamão",
                            ProteinPer100g = 0.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000027"),
                            CaloriesPer100g = 50.0,
                            CarbsPer100g = 13.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Abacaxi",
                            ProteinPer100g = 0.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000028"),
                            CaloriesPer100g = 60.0,
                            CarbsPer100g = 15.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.40000000000000002,
                            IsCustom = false,
                            Name = "Manga",
                            ProteinPer100g = 0.80000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000029"),
                            CaloriesPer100g = 28.0,
                            CarbsPer100g = 4.4000000000000004,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.5,
                            IsCustom = false,
                            Name = "Couve Cozida",
                            ProteinPer100g = 2.2000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000030"),
                            CaloriesPer100g = 23.0,
                            CarbsPer100g = 3.7999999999999998,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Espinafre Cozido",
                            ProteinPer100g = 2.8999999999999999
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000031"),
                            CaloriesPer100g = 40.0,
                            CarbsPer100g = 9.3000000000000007,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.10000000000000001,
                            IsCustom = false,
                            Name = "Cebola",
                            ProteinPer100g = 1.1000000000000001
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000032"),
                            CaloriesPer100g = 149.0,
                            CarbsPer100g = 33.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.5,
                            IsCustom = false,
                            Name = "Alho",
                            ProteinPer100g = 6.4000000000000004
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000033"),
                            CaloriesPer100g = 158.0,
                            CarbsPer100g = 31.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.90000000000000002,
                            IsCustom = false,
                            Name = "Macarrão Cozido",
                            ProteinPer100g = 5.7999999999999998
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000034"),
                            CaloriesPer100g = 265.0,
                            CarbsPer100g = 49.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 3.5,
                            IsCustom = false,
                            Name = "Pão Integral",
                            ProteinPer100g = 9.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000035"),
                            CaloriesPer100g = 428.0,
                            CarbsPer100g = 66.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 14.0,
                            IsCustom = false,
                            Name = "Biscoito Cream Cracker",
                            ProteinPer100g = 10.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000036"),
                            CaloriesPer100g = 567.0,
                            CarbsPer100g = 16.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 49.0,
                            IsCustom = false,
                            Name = "Amendoim",
                            ProteinPer100g = 26.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000037"),
                            CaloriesPer100g = 553.0,
                            CarbsPer100g = 30.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 44.0,
                            IsCustom = false,
                            Name = "Castanha de Caju",
                            ProteinPer100g = 18.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000038"),
                            CaloriesPer100g = 579.0,
                            CarbsPer100g = 22.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 50.0,
                            IsCustom = false,
                            Name = "Amêndoa",
                            ProteinPer100g = 21.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000039"),
                            CaloriesPer100g = 535.0,
                            CarbsPer100g = 60.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 30.0,
                            IsCustom = false,
                            Name = "Chocolate ao Leite",
                            ProteinPer100g = 8.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000040"),
                            CaloriesPer100g = 304.0,
                            CarbsPer100g = 82.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.0,
                            IsCustom = false,
                            Name = "Mel",
                            ProteinPer100g = 0.29999999999999999
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000041"),
                            CaloriesPer100g = 387.0,
                            CarbsPer100g = 100.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.0,
                            IsCustom = false,
                            Name = "Açúcar Refinado",
                            ProteinPer100g = 0.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000042"),
                            CaloriesPer100g = 207.0,
                            CarbsPer100g = 24.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 11.0,
                            IsCustom = false,
                            Name = "Sorvete de Baunilha",
                            ProteinPer100g = 3.5
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000043"),
                            CaloriesPer100g = 266.0,
                            CarbsPer100g = 33.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 10.0,
                            IsCustom = false,
                            Name = "Pizza de Queijo",
                            ProteinPer100g = 12.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000044"),
                            CaloriesPer100g = 250.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 20.0,
                            IsCustom = false,
                            Name = "Hambúrguer Bovino",
                            ProteinPer100g = 17.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000045"),
                            CaloriesPer100g = 128.0,
                            CarbsPer100g = 0.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 2.7000000000000002,
                            IsCustom = false,
                            Name = "Tilápia Grelhada",
                            ProteinPer100g = 26.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000046"),
                            CaloriesPer100g = 99.0,
                            CarbsPer100g = 0.90000000000000002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 0.29999999999999999,
                            IsCustom = false,
                            Name = "Camarão Cozido",
                            ProteinPer100g = 24.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000047"),
                            CaloriesPer100g = 160.0,
                            CarbsPer100g = 9.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 15.0,
                            IsCustom = false,
                            Name = "Abacate",
                            ProteinPer100g = 2.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000048"),
                            CaloriesPer100g = 188.0,
                            CarbsPer100g = 3.7000000000000002,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 18.0,
                            IsCustom = false,
                            Name = "Creme de Leite",
                            ProteinPer100g = 2.7000000000000002
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000049"),
                            CaloriesPer100g = 370.0,
                            CarbsPer100g = 6.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 5.0,
                            IsCustom = false,
                            Name = "Whey Protein",
                            ProteinPer100g = 75.0
                        },
                        new
                        {
                            Id = new Guid("00000000-0000-0000-0000-000000000050"),
                            CaloriesPer100g = 471.0,
                            CarbsPer100g = 64.0,
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            FatPer100g = 20.0,
                            IsCustom = false,
                            Name = "Granola",
                            ProteinPer100g = 10.0
                        });
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.Meal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("DailySummaryId")
                        .HasColumnType("uuid");

                    b.Property<TimeOnly?>("EatenAt")
                        .HasColumnType("time without time zone");

                    b.Property<string>("MealType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TotalCalories")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("TotalCarbsG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("TotalFatG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("TotalProteinG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("DailySummaryId");

                    b.HasIndex("PatientId");

                    b.ToTable("Meals", "nutri_patient");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.MealItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("Calories")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.Property<decimal>("CarbsG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FatG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<Guid?>("FoodId")
                        .HasColumnType("uuid");

                    b.Property<string>("FoodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("MealId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ProteinG")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("QuantityG")
                        .HasPrecision(7, 2)
                        .HasColumnType("numeric(7,2)");

                    b.HasKey("Id");

                    b.HasIndex("FoodId");

                    b.HasIndex("MealId");

                    b.ToTable("MealItems", "nutri_patient");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<decimal?>("HeightCm")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("OnboardingCompleted")
                        .HasColumnType("boolean");

                    b.Property<string>("Phone")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Sex")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("patients", "nutri_patient");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.PatientGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityLevel")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DailyCalorieGoal")
                        .HasColumnType("integer");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TargetWeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("PatientGoals", "nutri_patient");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.WeightHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("RecordedAt")
                        .HasColumnType("date");

                    b.Property<decimal>("WeightKg")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("PatientId", "RecordedAt");

                    b.ToTable("WeightHistories", "nutri_patient");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.DailySummary", b =>
                {
                    b.HasOne("NutriHubPatient.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.Food", b =>
                {
                    b.HasOne("NutriHubPatient.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("CreatedByPatientId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.Meal", b =>
                {
                    b.HasOne("NutriHubPatient.Domain.Entities.DailySummary", null)
                        .WithMany("Meals")
                        .HasForeignKey("DailySummaryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NutriHubPatient.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.MealItem", b =>
                {
                    b.HasOne("NutriHubPatient.Domain.Entities.Food", null)
                        .WithMany()
                        .HasForeignKey("FoodId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NutriHubPatient.Domain.Entities.Meal", null)
                        .WithMany("Items")
                        .HasForeignKey("MealId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.PatientGoal", b =>
                {
                    b.HasOne("NutriHubPatient.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.WeightHistory", b =>
                {
                    b.HasOne("NutriHubPatient.Domain.Entities.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.DailySummary", b =>
                {
                    b.Navigation("Meals");
                });

            modelBuilder.Entity("NutriHubPatient.Domain.Entities.Meal", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
