name: NutriHub CI/CD

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:

  # BUILD STAGE
  build-auth:
    name: Build Auth
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore backend/NutriHubAuth/NutriHubAuth.slnx
      - run: dotnet build backend/NutriHubAuth/NutriHubAuth.slnx --configuration Release --no-restore


  build-patient:
    name: Build Patient
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore backend/NutriHubPatient/NutriHubPatient.slnx
      - run: dotnet build backend/NutriHubPatient/NutriHubPatient.slnx --configuration Release --no-restore


  build-clinic:
    name: Build Clinic
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - run: dotnet restore backend/NutriHubClinic/NutriHubClinic.slnx
      - run: dotnet build backend/NutriHubClinic/NutriHubClinic.slnx --configuration Release --no-restore


  build-frontend:
    name: Build Frontend
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-node@v5
        with:
          node-version: '22'
          cache: 'npm'
          cache-dependency-path: './frontend/package-lock.json'

      - name: Install Dependencies
        run: npm ci
        working-directory: ./frontend

      - name: Build
        run: npm run build
        working-directory: ./frontend


  # TEST STAGE
  test-auth:
    name: Test Auth
    runs-on: ubuntu-latest
    needs: build-auth

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore Tests
        run: dotnet restore backend/NutriHubAuth/tests/NutriHubAuth.Tests/NutriHubAuth.Tests.csproj

      - name: Run Tests
        run: dotnet test backend/NutriHubAuth/tests/NutriHubAuth.Tests/NutriHubAuth.Tests.csproj --configuration Release --no-restore --verbosity normal

  test-patient:
    name: Test Patient
    runs-on: ubuntu-latest
    needs: build-patient

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore Tests
        run: dotnet restore backend/NutriHubPatient/tests/NutriHubPatient.Tests/NutriHubPatient.Tests.csproj

      - name: Run Tests
        run: dotnet test backend/NutriHubPatient/tests/NutriHubPatient.Tests/NutriHubPatient.Tests.csproj --configuration Release --no-restore --verbosity normal

  test-clinic:
    name: Test Clinic
    runs-on: ubuntu-latest
    needs: build-clinic

    steps:
      - uses: actions/checkout@v5

      - uses: actions/setup-dotnet@v5
        with:
          dotnet-version: '10.0.x'

      - name: Restore Tests
        run: dotnet restore backend/NutriHubClinic/tests/NutriHubClinic.Tests/NutriHubClinic.Tests.csproj

      - name: Run Tests
        run: dotnet test backend/NutriHubClinic/tests/NutriHubClinic.Tests/NutriHubClinic.Tests.csproj --configuration Release --no-restore --verbosity normal